"""Deterministic project generation primitives used by the CLI."""

from __future__ import annotations

import re
from pathlib import Path


class GenerationError(ValueError):
    """Raised when a project cannot be generated safely."""


class ProjectGenerator:
    """Generate a minimal, testable FastAPI project from versioned templates.

    The generator deliberately creates files rather than copying the Backbone
    repository itself. This keeps generated applications independent from the
    generator's development tree and gives template versions a stable contract.
    """

    def __init__(self, name: str, output: Path, include_ai: bool = False, force: bool = False):
        self.name = name
        self.output = output
        self.include_ai = include_ai
        self.force = force
        self.package = self._package_name(name)

    @staticmethod
    def _package_name(name: str) -> str:
        normalized = re.sub(r"[^A-Za-z0-9_-]+", "-", name).strip("-").lower()
        package = normalized.replace("-", "_")
        if not package or not re.match(r"^[a-zA-Z_]", package) or not re.match(
            r"^[a-zA-Z_][a-zA-Z0-9_]*$", package
        ):
            raise GenerationError(f"invalid project name: {name!r}")
        return package

    def generate(self) -> Path:
        target = (self.output / self.name).resolve()
        if target.exists():
            if not target.is_dir():
                raise GenerationError(f"target exists and is not a directory: {target}")
            if any(target.iterdir()) and not self.force:
                raise GenerationError(f"target directory is not empty: {target}")
        else:
            target.mkdir(parents=True)

        files = self._files()
        for relative, content in files.items():
            destination = target / relative
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(content, encoding="utf-8")
        return target

    def _files(self) -> dict[str, str]:
        files = {
            "src/__init__.py": "",
            f"src/{self.package}/__init__.py": '"""Generated FastAPI application."""\n',
            f"src/{self.package}/app.py": APP_TEMPLATE.format(package=self.package),
            "tests/test_app.py": TEST_TEMPLATE.format(package=self.package),
            ".env.example": ENV_TEMPLATE,
            ".gitignore": GITIGNORE_TEMPLATE,
            "pyproject.toml": PROJECT_TEMPLATE.format(package=self.package),
            "README.md": README_TEMPLATE.format(name=self.name, package=self.package),
        }
        if self.include_ai:
            files.update(
                {
                    f"src/{self.package}/ai/__init__.py": AI_INIT_TEMPLATE,
                    f"src/{self.package}/ai/agent.py": AI_AGENT_TEMPLATE,
                    f"src/{self.package}/ai/config.py": AI_CONFIG_TEMPLATE,
                    f"tests/test_ai.py": AI_TEST_TEMPLATE.format(package=self.package),
                }
            )
            files["pyproject.toml"] += "\n" + AI_PROJECT_EXTRA
        return files


APP_TEMPLATE = '''"""Application composition root."""\n\nfrom fastapi import FastAPI\n\n\ndef create_app() -> FastAPI:\n    app = FastAPI(title="{package}")\n\n    @app.get("/api/health/live")\n    async def live() -> dict[str, str]:\n        return {{"status": "ok"}}\n\n    return app\n'''

TEST_TEMPLATE = '''from {package}.app import create_app\n\n\ndef test_application_factory() -> None:\n    app = create_app()\n    assert app.title == "{package}"\n'''

ENV_TEMPLATE = """ENVIRONMENT=development\nDATABASE_URL=sqlite+aiosqlite:///./app.db\nAI_ENABLED=false\nAI_MODEL=\n"""

GITIGNORE_TEMPLATE = """.venv/\n__pycache__/\n.pytest_cache/\n.ruff_cache/\n.mypy_cache/\n.env\n*.db\n"""

PROJECT_TEMPLATE = '''[build-system]\nrequires = ["setuptools>=70"]\nbuild-backend = "setuptools.build_meta"\n\n[project]\nname = "{package}"\nversion = "0.1.0"\ndescription = "Generated FastAPI application"\nrequires-python = ">=3.11"\ndependencies = [\n    "fastapi>=0.115,<1.0",\n    "uvicorn[standard]>=0.30,<1.0",\n]\n\n[project.optional-dependencies]\ndev = [\n    "httpx>=0.28,<1.0",\n    "pytest>=8.4,<9.0",\n    "ruff>=0.6,<1.0",\n]\n\n[tool.pytest.ini_options]\ntestpaths = ["tests"]\n\n[tool.ruff]\nline-length = 100\ntarget-version = "py311"\n\n[tool.setuptools.packages.find]\nwhere = ["src"]\n'''

README_TEMPLATE = '''# {name}\n\nGenerated by FastAPI Backbone.\n\n## Development\n\n```bash\nuv sync --extra dev\nuv run pytest\nuv run ruff check .\n```\n\nThe application factory is `{package}.app:create_app`.\n'''

AI_INIT_TEMPLATE = '''"""Optional AI application architecture."""\n\nfrom .agent import create_agent\n\n__all__ = ["create_agent"]\n'''

AI_CONFIG_TEMPLATE = '''"""AI configuration kept separate from business logic."""\n\nfrom pydantic_settings import BaseSettings, SettingsConfigDict\n\n\nclass AISettings(BaseSettings):\n    model_config = SettingsConfigDict(env_prefix="AI_", extra="ignore")\n\n    enabled: bool = False\n    model: str = ""\n    timeout_seconds: float = 30.0\n    max_retries: int = 2\n'''

AI_AGENT_TEMPLATE = '''"""Pydantic AI boundary for the generated application."""\n\nfrom pydantic_ai import Agent\n\n\ndef create_agent(model: str) -> Agent:\n    """Create an agent from a runtime model identifier.\n\n    The application supplies the model identifier/configuration; business code\n    does not depend on a concrete provider SDK.\n    """\n    return Agent(model=model)\n'''

AI_TEST_TEMPLATE = '''import pytest\n\n\ndef test_ai_profile_is_optional() -> None:\n    pytest.importorskip("pydantic_ai")\n    from {package}.ai.agent import create_agent\n\n    assert create_agent is not None\n'''

AI_PROJECT_EXTRA = '''[project.optional-dependencies]\nai = [\n    "pydantic-ai>=1.0,<2.0",\n]\n'''
