"""Versioned source templates used by the project generator."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


TEMPLATE_VERSION = "0.2.0"


@dataclass(frozen=True, slots=True)
class TemplateFile:
    path: str
    content: str


_SOURCE_DIRS = ("api", "auth", "core", "identity")


def _source_root() -> Path:
    return Path(__file__).resolve().parent


def _render_source(package: str, include_ai: bool) -> list[TemplateFile]:
    root = _source_root()
    directories = _SOURCE_DIRS + (("ai",) if include_ai else ())
    files: list[TemplateFile] = []
    for relative_dir in directories:
        source_dir = root / relative_dir
        if not source_dir.is_dir():
            raise RuntimeError(f"template source directory is missing: {source_dir}")
        for source in sorted(source_dir.rglob("*.py")):
            relative = source.relative_to(root)
            content = source.read_text(encoding="utf-8").replace("fastapi_backbone", package)
            files.append(TemplateFile(f"src/{package}/{relative.as_posix()}", content))

    app_source = root / "app.py"
    content = app_source.read_text(encoding="utf-8").replace("fastapi_backbone", package)
    files.append(TemplateFile(f"src/{package}/app.py", content))
    files.append(TemplateFile(f"src/{package}/__init__.py", '"""Generated FastAPI application."""\n'))
    return files


def render_default_template(
    package: str,
    project_name: str,
    *,
    include_ai: bool = False,
) -> tuple[TemplateFile, ...]:
    """Render the versioned production application template."""
    files = _render_source(package, include_ai)
    files.extend(
        (
            TemplateFile(
                "pyproject.toml",
                f'''[build-system]\nrequires = ["setuptools>=70"]\nbuild-backend = "setuptools.build_meta"\n\n[project]\nname = "{package}"\nversion = "0.1.0"\ndescription = "Production-grade FastAPI service generated by FastAPI Backbone."\nrequires-python = ">=3.11"\ndependencies = [\n    "fastapi>=0.115,<1.0",\n    "uvicorn[standard]>=0.30,<1.0",\n    "sqlalchemy[asyncio]>=2.0.30,<3.0",\n    "asyncpg>=0.29,<1.0",\n    "aiosqlite>=0.20,<1.0",\n    "alembic>=1.13,<2.0",\n    "pydantic>=2.8,<3.0",\n    "pydantic-settings>=2.4,<3.0",\n    "structlog>=24.4,<26.0",\n    "PyJWT>=2.9,<3.0",\n    "pwdlib[argon2]>=0.2,<1.0",\n]\n\n[project.optional-dependencies]\ndev = [\n    "httpx>=0.28,<1.0",\n    "pytest>=8.4,<9.0",\n    "pytest-asyncio>=1.4,<2.0",\n    "ruff>=0.6,<1.0",\n    "mypy>=1.11,<2.0",\n]\nai = ["pydantic-ai>=1.0,<2.0"]\n\n[tool.pytest.ini_options]\nasyncio_mode = "auto"\ntestpaths = ["tests"]\n\n[tool.ruff]\nline-length = 100\ntarget-version = "py311"\n\n[tool.ruff.lint]\nselect = ["E", "F", "I", "B", "UP"]\n\n[tool.mypy]\npython_version = "3.11"\nignore_missing_imports = true\n\n[tool.setuptools.packages.find]\nwhere = ["src"]\ninclude = ["{package}*"]\n''',
            ),
            TemplateFile(
                ".env.example",
                "ENVIRONMENT=development\nDEBUG=false\nDATABASE_URL=sqlite+aiosqlite:///./app.db\nAPP_NAME="
                + project_name
                + "\nAPP_VERSION=0.1.0\nAI_ENABLED=false\nAI_MODEL=\n",
            ),
            TemplateFile(
                ".gitignore",
                ".venv/\n__pycache__/\n.pytest_cache/\n.ruff_cache/\n.mypy_cache/\n.env\n*.db\n",
            ),
            TemplateFile(
                "main.py",
                f'''"""ASGI entrypoint for the generated service."""\n\nfrom {package}.app import create_app\n\napp = create_app()\n''',
            ),
            TemplateFile(
                "tests/test_app.py",
                f'''from {package}.app import create_app\nfrom {package}.core.config import Environment, Settings\n\n\ndef test_application_factory() -> None:\n    app = create_app(Settings.for_profile(Environment.TEST))\n    assert app.title == "{project_name}"\n\n\ndef test_liveness_route_is_registered() -> None:\n    app = create_app(Settings.for_profile(Environment.TEST))\n    assert any(route.path.endswith("/health/live") for route in app.routes)\n''',
            ),
            TemplateFile(
                "Dockerfile",
                '''FROM python:3.13-slim AS runtime\nWORKDIR /app\nENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1\nCOPY . /app\nRUN pip install --no-cache-dir .\nUSER nobody\nEXPOSE 8000\nCMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]\n''',
            ),
            TemplateFile(
                "docker-compose.yml",
                '''services:\n  db:\n    image: postgres:17-alpine\n    environment:\n      POSTGRES_DB: app\n      POSTGRES_USER: app\n      POSTGRES_PASSWORD: app\n    healthcheck:\n      test: ["CMD-SHELL", "pg_isready -U app -d app"]\n      interval: 5s\n      timeout: 5s\n      retries: 10\n  api:\n    build: .\n    environment:\n      ENVIRONMENT: production\n      DATABASE_URL: postgresql+asyncpg://app:app@db:5432/app\n    depends_on:\n      db:\n        condition: service_healthy\n    ports:\n      - "8000:8000"\n''',
            ),
            TemplateFile(
                "alembic.ini",
                '''[alembic]\nscript_location = %(here)s/alembic\nsqlalchemy.url = sqlite+aiosqlite:///./app.db\n''',
            ),
            TemplateFile(
                "alembic/env.py",
                f'''from alembic import context\nfrom sqlalchemy import pool\nfrom sqlalchemy.engine import Connection\nfrom sqlalchemy.ext.asyncio import async_engine_from_config\n\nfrom {package}.core.config import get_settings\nfrom {package}.core.database import Base\nfrom {package}.identity.models import User  # noqa: F401\nfrom {package}.identity.refresh_tokens import RefreshToken  # noqa: F401\n\nconfig = context.config\nsettings = get_settings()\nconfig.set_main_option("sqlalchemy.url", settings.database_url.replace("%", "%%"))\ntarget_metadata = Base.metadata\n\ndef run_migrations_offline() -> None:\n    context.configure(url=config.get_main_option("sqlalchemy.url"), target_metadata=target_metadata, literal_binds=True)\n    with context.begin_transaction():\n        context.run_migrations()\n\ndef do_run_migrations(connection: Connection) -> None:\n    context.configure(connection=connection, target_metadata=target_metadata)\n    with context.begin_transaction():\n        context.run_migrations()\n\nasync def run_async_migrations() -> None:\n    connectable = async_engine_from_config(config.get_section(config.config_ini_section, {{}}), prefix="sqlalchemy.", poolclass=pool.NullPool)\n    async with connectable.connect() as connection:\n        await connection.run_sync(do_run_migrations)\n    await connectable.dispose()\n\ndef run_migrations_online() -> None:\n    import asyncio\n    asyncio.run(run_async_migrations())\n\nif context.is_offline_mode():\n    run_migrations_offline()\nelse:\n    run_migrations_online()\n''',
            ),
            TemplateFile("alembic/versions/0001_initial.py", '''from alembic import op\nimport sqlalchemy as sa\n\nrevision = "0001_initial"\ndown_revision = None\nbranch_labels = None\ndepends_on = None\n\ndef upgrade() -> None:\n    op.create_table(\n        "users",\n        sa.Column("id", sa.String(length=36), nullable=False),\n        sa.Column("identifier", sa.String(length=320), nullable=False),\n        sa.Column("password_hash", sa.String(length=512), nullable=False),\n        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),\n        sa.PrimaryKeyConstraint("id"),\n        sa.UniqueConstraint("identifier"),\n    )\n    op.create_index("ix_users_identifier", "users", ["identifier"], unique=True)\n    op.create_table(\n        "refresh_tokens",\n        sa.Column("token_id", sa.String(), nullable=False),\n        sa.Column("subject", sa.String(), nullable=False),\n        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),\n        sa.Column("revoked", sa.Boolean(), nullable=False, server_default=sa.false()),\n        sa.PrimaryKeyConstraint("token_id"),\n    )\n    op.create_index("ix_refresh_tokens_subject", "refresh_tokens", ["subject"], unique=False)\n    op.create_index("ix_refresh_tokens_expires_at", "refresh_tokens", ["expires_at"], unique=False)\n\ndef downgrade() -> None:\n    op.drop_index("ix_refresh_tokens_expires_at", table_name="refresh_tokens")\n    op.drop_index("ix_refresh_tokens_subject", table_name="refresh_tokens")\n    op.drop_table("refresh_tokens")\n    op.drop_index("ix_users_identifier", table_name="users")\n    op.drop_table("users")\n'''),
            TemplateFile(
                ".github/workflows/ci.yml",
                '''name: CI\n\non:\n  push:\n  pull_request:\n\njobs:\n  quality:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: astral-sh/setup-uv@v6\n      - uses: actions/setup-python@v5\n        with:\n          python-version: "3.13"\n      - run: uv sync --extra dev\n      - run: uv run ruff check .\n      - run: uv run mypy src\n      - run: uv run pytest\n''',
            ),
            TemplateFile(
                "README.md",
                f'''# {project_name}\n\nGenerated by FastAPI Backbone template `{TEMPLATE_VERSION}`.\n\n## Run\n\n```bash\nuv sync --extra dev\nuv run pytest\nuv run uvicorn main:app --reload\n```\n\nThe generated service inherits Backbone configuration, database lifecycle, health,\nlogging, error handling, identity/authentication boundaries and async composition.\nSchema changes are managed exclusively through Alembic.\n\nAuthentication fails closed until the consuming application supplies an explicit\nauthentication composition factory.\n''',
            ),
        )
    )
    return tuple(files)
