"""Versioned source templates used by the project generator."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class TemplateFile:
    path: str
    content: str


def render_default_template(package: str, project_name: str) -> tuple[TemplateFile, ...]:
    """Return the current template set through a stable rendering API."""
    app_template = f'''"""Application composition root."""

from fastapi import FastAPI


def create_app() -> FastAPI:
    app = FastAPI(title="{package}")

    @app.get("/api/health/live")
    async def live() -> dict[str, str]:
        return {{"status": "ok"}}

    return app
'''

    test_template = f'''from {package}.app import create_app


def test_application_factory() -> None:
    app = create_app()
    assert app.title == "{package}"
'''

    return (
        TemplateFile(
            f"src/{package}/__init__.py",
            '"""Generated FastAPI application."""\n',
        ),
        TemplateFile(f"src/{package}/app.py", app_template),
        TemplateFile("tests/test_app.py", test_template),
        TemplateFile(
            ".env.example",
            "ENVIRONMENT=development\n"
            "DATABASE_URL=sqlite+aiosqlite:///./app.db\n"
            "AI_ENABLED=false\n"
            "AI_MODEL=\n",
        ),
        TemplateFile(
            ".gitignore",
            ".venv/\n"
            "__pycache__/\n"
            ".pytest_cache/\n"
            ".ruff_cache/\n"
            ".mypy_cache/\n"
            ".env\n"
            "*.db\n",
        ),
        TemplateFile(
            "README.md",
            f'''# {project_name}

Generated by FastAPI Backbone.

The application factory is `{package}.app:create_app`.
''',
        ),
    )
