apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-backbone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-backbone
  template:
    metadata:
      labels:
        app: fastapi-backbone
    spec:
      containers:
        - name: api
          image: ghcr.io/safuh/fastapi-backbone:0.1.0
          ports:
            - name: http
              containerPort: 8000
          envFrom:
            - configMapRef:
                name: fastapi-backbone-config
            - secretRef:
                name: fastapi-backbone-secret
          readinessProbe:
            httpGet:
              path: /api/health/ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health/live
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
            runAsNonRoot: true
