apiVersion: v1
kind: Secret
metadata:
  name: fastapi-backbone-secret
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://CHANGE_ME"
  JWT_SECRET_KEY: "CHANGE_ME_WITH_A_HIGH_ENTROPY_SECRET"
