apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-backbone
spec:
  ingressClassName: nginx
  rules:
    - host: api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fastapi-backbone
                port:
                  name: http
